### ISSUE TITLE
Not compatible with Angular 1.3?

### ISSUE THREAD

**Issue by fmalk** [Yappli/angular-css-injector#23]
I can't get it to work with Angular's latest version. Bower makes me choose between the required 1.2.6 from this project, or use my current 1.3. Installs fine if I choose 1.3, but breaks my controllers just by injecting it into a module.
Is it really not compatible at this point?

**Comment by raoel** [comment]
@avgustint: I had the same error when I initialize ng-app anywhere else than in the <html>-tag. Put it there and it might work.

Angular 1.3.13 works fine here. If it doesn't work for you, maybe you can provide an example of the error?

**Comment by rolbr** [comment]
Angular 1.3.11 works fine here.

I'm using `<html id="HwwApp" ng-controller="AppCtrl">` and then bootstrap the app manually on `deviceready` (building with PhoneGap)

Anyways. I'm currently looking to switch over to [AngularCSS](https://github.com/door3/angular-css), since it provides a wealth of features, like injecting CSS based on active routes or directives. Maybe you could join forces?

**Comment by archanak62** [comment]
It works with angular v1.3.6
